### PR TITLE
Allow adapters to run test suite with their db

### LINKED ISSUE #19: Database adapter test suite?
Should we have a test suite new database adapter can run against to check compatibility with the spec? Currently writing docs for it, I feel like that'd make it much easier.

This might require having a repo setup with the tests and a bunch of other niceties (e.g. linting) which developers can simply clone to write a new adapter.

### PR DESCRIPTION
**Pull request by mxstbr**
This adds a simple script that makes it possible to run our own test suite against a newly written adapter. Usage would be like so:

## Testing your adapter

`micro-analytics` contains an test suite to verify everything works as expected. We also export this test suite to make it possible to verify your adapter works as expected!

To run our test suite with your adapter (we recommend doing this in CI too) you only have to do three steps:

First, `npm install --save-dev micro-analytics-cli` to get the test suite.
Second, create a new file called `test.js` which contains this code: (don't forget to replace `'./index'` with the relative path to your main entry file!)

```JS
#!/usr/bin/env node
const test = require('micro-analytics-cli/adapter-test')

test('./index')
```

Finally, run our test suite with your db adapter with `node test.js`! 🎉

---- 

@relekang I've published a pre-release version containing this change under `micro-analytics-cli@dev`. Mind trying this on your `micro-analytics-adapter-redis` and seeing if it works?

Closes #19

### CODE REVIEW

**Comment by mxstbr** [comment]
Hm, I just tried this for the `flat-file-db` adapter and Jest complains:

```
No tests found
No files found in /path/micro-analytics-adapter-flat-file-db/node_modules/micro-analytics-cli.
Make sure Jest's configuration does not exclude this directory.
To set up Jest, make sure a package.json file exists.
Jest Documentation: facebook.github.io/jest/docs/configuration.html
```

The tests exist though, everything is exactly where it needs to be... Any ideas what's going wrong here?

**Comment by mxstbr** [comment]
This is a bug upstream in `jesthaste-map` according to @cpojer, trying to get a fix in there!

**Comment by mxstbr** [comment]
Okay I've managed to circumvent the bug with a super ugly and slow, but working, hack.

I npm link the adapter, clone the whole micro-analytics project to /tmp/, install the dependencies, run the tests with the adapter and then delete the temp folder again.

I've verified this works with the flat-file-db adapter. @relekang would you mind giving this a try?

**Comment by relekang** [comment]
This looks neat 🙂

I did not get it to run on the redis adapter 😕

```
> micro-analytics-cli@1.1.0 test /private/tmp/micro-analytics-adapter-test-suite
> jest

 FAIL  tests/atomicity.test.js
  ● Test suite failed to run

    ProcessTerminatedError: cancel after 2 retries!

      at Farm.<anonymous> (node_modules/worker-farm/lib/farm.js:81:25)
      at Array.forEach (native)
      at Farm.<anonymous> (node_modules/worker-farm/lib/farm.js:75:36)
      at ontimeout (timers.js:365:14)
      at tryOnTimeout (timers.js:237:5)
      at Timer.listOnTimeout (timers.js:207:5)

A worker process has quit unexpectedly! Most likely this an initialization error.
npm ERR! Test failed.  See above for more details.
~/dev/micro-analytics-adapter-redis
```

**Comment by mxstbr** [comment]
Hmm, will take a look later!

**Comment by mxstbr** [comment]
Picking this back up, switching to `mocha` instead of Jest has resolved the "Test can't run" error. Now working on making it a solid test suite, should be good to go after I'm done!

**Comment by mxstbr** [comment]
Okay this works now. Slightly changed instructions, but it's largely the same! 🎉

The tests of the main repo now test the main repo, but they can also be used to test any third party adapter. I'll do the `redis` adapter now to showcase how it works!

> Note: Except the `flat-file-db` one—that will be a bit tricky, since that's also required inside `micro-analytics`, not sure if I can get that tested just yet. Will work on that next!

**Comment by mxstbr** [comment]
Damn this is still failing due to `babel-register`. Will get it sorted soon! We're _really_ close now.

**Comment by relekang** [comment]
🤔 Yeah, probably because we don't get the dev dependencies of a dependency. Adding the necessary dependencies in the adapter might be a solution?

**Comment by mxstbr** [comment]
I'm `npm install`ing them actually, see `adapter-test.js`, but babel can't find the preset because it looks from the root `cwd` instead of the `__dirname`. 😕

**Comment by jimthedev** [comment]
I appreciate the attempt to use Node for this but it might be easier to keep node out of the equation when triggering the tests to be run. The invocation seems to work if you do it manually and don't try to use require. 

What if an adapter could just list micro-analytics-cli as a node devDependency then trigger the tests via bash/npm script.  The micro-analytics-cli would first npm install the dependencies but then would manually copy the adapter from the cwd into the child node_modules folder of the cli. The idea here is that the invocation of node doesn't happen until the dependency structure has been setup using just bash.  The bash command would look something like `node node_modules/micro-analytics-cli/adapter-test.js micro-analytics-adapter-redis`

**Comment by mxstbr** [comment]
If you think that could work out please take a stab at it! I'm really stuck here.

**Comment by jimthedev** [comment]
I'll see what I can scrape together.

**Comment by relekang** [comment]
I think we also might need an adapter test suite that has a few basic unit tests, since a test that fails for the micro-analytics project might be hard to track down for people who are not very familiar with the codebase. What I am suggestion is to have `micro-analytics-cli/adapter-tests/unit-tests.js` and `micro-analytics-cli/adapter-tests/integration-tests.js`. I have [started on the unit tests](https://github.com/relekang/micro-analytics/compare/sse...relekang:adapter-tests).

What do you think?

**Comment by mxstbr** [comment]
Sure!

**Comment by relekang** [comment]
Closing this as I think we need to start over if we want to revisit this after the #69. However, I think the approach of writing specific tests for adapters works nicely so far.

**Pull request closed without merging**
