### PR TITLE
Add more adapter tests

### PR DESCRIPTION
**Pull request by relekang**
- [x] Check return type of adapter functions
- [x] `get` of key that has no views
- [x] `getAll` filtering of pathnames
- [x] `get` filtering of time
- [x] `getAll` filtering of time

### CODE REVIEW

**Comment by relekang** [comment]
@mxstbr If you have any suggestions for tests we need for adapters please add to the list the PR description.

**Comment by mxstbr** [comment]
Can't think of anything else at the moment, this is looking great!

**Comment by relekang** [comment]
This is ready for review now ✌️

**Comment by mxstbr** [comment]
We should add a shitton more tests with a bunch of different scenarios (and edge cases?) that could happen so we make sure all adapters are 100% correct, but that's a possible enhancement in the future. This is great!

**Comment by relekang** [comment]
Yeah, I agree that we can do that outside this PR.

**Pull request merged**
