### PR TITLE
Allow send additional data via meta key

### PR DESCRIPTION
**Pull request by 7rulnik**
@relekang @mxstbr 
It should resolve https://github.com/micro-analytics/micro-analytics-cli/issues/24

But I think that opportunity to pass something more complicated than strings will be cool. How we should pass arrays or objects?

### CODE REVIEW

**Comment by relekang** [comment]
> But I think that opportunity to pass something more complicated than strings will be cool. How we should pass arrays or objects?

I am kind of thorn between this would be nice to have and it is a good thing to have the restriction. 
What do you think @mxstbr? We can add it later under another param name e.g. `meta_json`.

If we want to support more complex data structures I think urlencoded json is a good way to go.

**Comment by 7rulnik** [comment]
Honestly I don't think that `?meta=k1:v1,k2:v2` is a good way for passing additional data.

1. User should generate this string
2. Maximum lenght of url — [2000 symbols](http://stackoverflow.com/questions/417142/what-is-the-maximum-length-of-a-url-in-different-browsers)
3. Support meta and meta_json will be pain. 2 keys that do same things.
4. We need additional logic for parsing `?meta=k1:v1,k2:v2`. It's not really hard, but it can be easier.

I think that POST is correct way for passing meta.
```js
fetch('/users', {
  method: 'POST',
  headers: {
    'Content-Type': 'application/json'
  },
  body: JSON.stringify({
    meta: {…},
  })
})
```
And `JSON.parse` on server.

I prefer to decide how it will be before shipping something for users.

**Comment by relekang** [comment]
I agree, I am thinking that it would be great if we turned it so that get only reads and post is the way to put things into the db.

**Comment by 7rulnik** [comment]
If we split get and put it would be major release, so for now we can merge this PR and release it as minor version. After this I can start splitting.

**Comment by mxstbr** [comment]
> it would be great if we turned it so that get only reads

I'm not a fan of that, I quite like that `GET` also increments because it supports this pattern: (which is what I built `micro-analytics` for initially)

```JS
window.onload = () => {
  fetch(`my-analytics.com/${window.location.href}`)
    .then(data => console.log(`${data.views} views`)) 
}
```

I do agree that `?meta` isn't the best choice though, we could just do `POST` to add meta data but `GET` still increments?

**Comment by relekang** [comment]
>I do agree that ?meta isn't the best choice though, we could just do POST to add meta data but `GET` still increments?

👍

**Comment by relekang** [comment]
Closing this as we want to revisit without meta in GET requests. The [meta-branch][] contains a wip version of that on top of the lerna restructure.


[meta-branch]: https://github.com/micro-analytics/micro-analytics-cli/compare/refactor/fix-test-listen...meta

**Pull request closed without merging**
