### PR TITLE
Use adapter-memory to make autodeployment work

### PR DESCRIPTION
**Pull request by relekang**
Trying again :v:

This uses an in memory database to get around the do not write restriction of now.sh

### CODE REVIEW

**Comment by mxstbr** [comment]
Won't this mean everytime we deploy all data is lost?

**Comment by relekang** [comment]
True, it is not any different from flat-file-db on now. I was thinking we should use the autodeploy just for demo things and then ship to internal the same way we do with cli.micro-analytics.io because of db secrets stuff.

**Comment by mxstbr** [comment]
Sure, that sounds good to me, the autodeploy could be `demo.micro-analytics.com` and we link to `demo.micro-analytics.com/visited` which is just how many people have viewed the demo 😉

**Comment by relekang** [comment]
> link to demo.micro-analytics.com/visited which is just how many people have viewed the demo 

🙌

**Pull request merged**
