### PR TITLE
Lerna 🐉

### LINKED ISSUE #38: Tests throw "ReferenceError: async is not defined"
I am pulling my hair out trying to get the aysnc-to-gen stuff going. I am running node 6.2 (and I have jest-cli globally). 

```
ReferenceError: async is not defined
      
      at Object.<anonymous> (node_modules/micro-analytics-adapter-flat-file-db/index.js:11:8)
      at Object.<anonymous> (src/db.js:9:13)
      at Object.<anonymous> (src/index.js:4:12)
      at Object.<anonymous> (tests/items.test.js:5:17)
```

for all three tests. Basically, jest isn't applying the transforms but I have no idea why. Do you experience this as well?

### PR DESCRIPTION
**Pull request by relekang**
- [x] Add lerna
- [x] Separate adapter-utils to own package
- [x] Move in adapter-flat-file-db (keep git history to keep contributions)
- [x] Move in adapter-memory
- [x] Run tests and lint from main package.json
- [x] Make all packages follow same .babelrc
- [x] Create a new top level readme
- [x] Make tests work
- [x] Add note in main readme about community adapters
- [x] Fix files in all packages

Fixes #38, #45

### CODE REVIEW

**Comment by relekang** [comment]
@mxstbr This is starting to take shape 🎉 

I am thinking that we should switch the database mocking with the memory adapter. I think the new setup broke the jest mocking of flat-file-db.

**Comment by mxstbr** [comment]
Let's publish a canary version once tests are passing to make sure everything is working as expected?

**Comment by relekang** [comment]
This is ready for a review now :v:

There is one little problem were it uses the wrong file in adapter-utils in node 6. Not sure why it does not work. (https://github.com/micro-analytics/micro-analytics-cli/pull/69/files#diff-3c7d545fdc1d88cf431afbe629f0f29cR3)

**Comment by relekang** [comment]
Also, the canary releases works

```
~/dev/test-ma » yarn add micro-analytics-adapter-flat-file-db@1.3.0-alpha.13dcefb3 micro-analytics-adapter-memory@1.0.0-alpha.13dcefb3 micro-analytics-adapter-utils@0.0.1-alpha.13dcefb3 micro-analytics-cli@2.2.0-alpha.13dcefb3
yarn add v0.24.5
[1/4] 🔍  Resolving packages...
[2/4] 🚚  Fetching packages...
[3/4] 🔗  Linking dependencies...
warning "micro-analytics-adapter-flat-file-db@1.3.0-alpha.13dcefb3" has incorrect peer dependency "micro-analytics-cli@^1.2.0".
[4/4] 📃  Building fresh packages...
success Saved 0 new dependencies.
✨  Done in 0.68s.
------------------------------------------------------------
~/dev/test-ma » micro-analytics
micro-analytics listening on 0.0.0.0:3000
  with adapter flat-file-db
  with server side events

------------------------------------------------------------
~/dev/test-ma » micro-analytics --adapter memory
micro-analytics listening on 0.0.0.0:3000
  with adapter memory
  with server side events

------------------------------------------------------------
~/dev/test-ma » micro-analytics --adapter memory &
[1] 89003
------------------------------------------------------------
~/dev/test-ma » micro-analytics listening on 0.0.0.0:3000
  with adapter memory
  with server side events

------------------------------------------------------------
~/dev/test-ma » curl localhost:3000/test
{"views":1}
```

**Comment by relekang** [comment]
Finally got the build green 🎉 Do you think we can ship this @mxstbr?

**Comment by mxstbr** [comment]
Let's shipit!

**Comment by mxstbr** [comment]
Nice work, thanks for fighting through that!

**Comment by relekang** [comment]
This is a breaking change for micro-analytics-cli, since we moved adapter-utils to another package. Thus, we need to bump major for that package. I will release:
micro-analytics-cli 3.0.0
micro-analytics-adapter-utils 1.0.0
micro-analytics-adapter-memory 1.0.1
micro-analytics-adapter-flat-file-db 1.3.1

and then for next release we can make lerna do all the work I think.

**Pull request merged**
